name: Build
on:
  push:
    paths-ignore:
      - 'LICENSE'
      - 'README.md'
  schedule:
    - cron: '0 12 * * 1'
  workflow_dispatch:
jobs:
  build:
    name: Build or Publish
    runs-on: ubuntu-latest
    concurrency:
      group: ci-${{ github.ref }}-${{ matrix.tag }}
      cancel-in-progress: true
    strategy:
      fail-fast: false
      matrix:
        tag: ['base', 'base-devel']
    env:
      is_release: ${{ github.event_name != 'push' }}
      image_tag: '${{ vars.DOCKERHUB_USERNAME }}/archlinux:${{ matrix.tag }}'
      latest_tag: '${{ vars.DOCKERHUB_USERNAME }}/archlinux:latest'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        if: env.is_release == 'true'
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build
        run: |
          cp mirrorlist '${{ matrix.tag }}'
          docker buildx build \
            -t '${{ env.image_tag }}' \
            --load \
            '${{ matrix.tag }}'
      - name: Push
        if: env.is_release == 'true'
        run: |
          docker push '${{ env.image_tag }}'
      - name: Push latest tag
        if: env.is_release == 'true' && matrix.tag == 'base'
        run: |
          docker tag \
            '${{ env.image_tag }}' \
            '${{ env.latest_tag }}'
          docker push '${{ env.latest_tag }}'
